config/routes.rb
Rails.application.routes.draw do
  root to: 'app/front#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  namespace :admin do
    root to: 'admin#root'

    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :meta_tags do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_adwords do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_analytics_tracks do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :settings, only: [] do
      collection do
        get '/:config', to: 'settings#edit', as: ''
        put '/:config', to: 'settings#update', as: 'update'
      end
    end
  end

  # Errors routes
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Dashboard route engine
  mount KepplerGaDashboard::Engine, at: 'admin/dashboard', as: 'dashboard'
end

app/models/google_adword.rb
# GoogleAdword Model
class GoogleAdword < ActiveRecord::Base
  include ActivityHistory
  include CloneRecord

  validates_uniqueness_of :url

  def self.get_by_url(url)
    find_by_url(url)
  end

  def self.search_field
    :campaign_name_or_description_cont
  end
end

app/controllers/admin/google_adwords_controller.rb
module Admin
  # GoogleAdwordsController
  class GoogleAdwordsController < AdminController
    before_action :set_google_adword, only: [:show, :edit, :update, :destroy]
    before_action :show_history, only: [:index]

    # GET /google_adwords
    def index
      @q = GoogleAdword.ransack(params[:q])
      google_adwords = @q.result(distinct: true)
      @objects = google_adwords.page(@current_page)
      @total = google_adwords.size
      if !@objects.first_page? && @objects.size.zero?
        redirect_to(
          google_adwords_path(page: @current_page.to_i.pred, search: @query)
        )
      end
    end

    # GET /google_adwords/1
    def show
    end

    # GET /google_adwords/new
    def new
      @google_adword = GoogleAdword.new
    end

    # GET /google_adwords/1/edit
    def edit
    end

    # POST /google_adwords
    def create
      @google_adword = GoogleAdword.new(google_adword_params)

      if @google_adword.save
        redirect(@google_adword, params)
      else
        render :new
      end
    end

    # PATCH/PUT /google_adwords/1
    def update
      if @google_adword.update(google_adword_params)
        redirect(@google_adword, params)
      else
        render :edit
      end
    end

    def clone
      @google_adword = GoogleAdword.clone_record params[:google_adword_id]

      if @google_adword.save
        redirect_to admin_meta_tags_path
      else
        render :new
      end
    end

    # DELETE /google_adwords/1
    def destroy
      @google_adword.destroy
      redirect_to(
        admin_google_adwords_path, notice: actions_messages(@google_adword)
      )
    end

    def destroy_multiple
      GoogleAdword.destroy redefine_ids(params[:multiple_ids])
      redirect_to(
        admin_google_adwords_path(page: @current_page, search: @query),
        notice: actions_messages(GoogleAdword.new)
      )
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_google_adword
      @google_adword = GoogleAdword.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def google_adword_params
      params.require(:google_adword).permit(
        :url, :campaign_name, :description, :script
      )
    end

    def show_history
      get_history(GoogleAdword)
    end
  end
end

app/views/admin/google_adwords/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.code.css_class('md-light')
		= t("keppler.models.singularize.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		.collection.with-header
			.collection-header
				%h5
					= t("keppler.titles.history")
			- @activities.each do |activity|
				- if activity.trackable_type.eql? 'Session'
					= render partial: "public_activity/session/#{activity.key.split(".").second}", locals: { activity: activity, method: 'campaign_name' }
				- else
					= render partial: "public_activity/layout/#{activity.key.split(".").second}", locals: { activity: activity, method: 'campaign_name' }

app/views/admin/google_adwords/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to admin_google_adwords_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				.card-content
					= simple_form_for [:admin, @google_adword] do |f|
						.row
							= f.input :url
							= f.input :campaign_name
							= f.input :description, input_html: {class: "materialize-textarea"}
							= f.input :script, input_html: {class: "materialize-textarea"}

							.form-actions.right
								= f.button :submit, t("keppler.actions.save"), name: "_save"
								= f.button :submit, t("keppler.actions.save_and_add_another"), name: "_add_other"

app/views/admin/google_adwords/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, GoogleAdword
			= link_to edit_admin_google_adword_path(@google_adword), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.edit") do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.code.css_class("md-light")
		= t("keppler.models.singularize.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.card-content
		%ul.list
			%li.list-row
				.display-label= t("activerecord.attributes.google_adword.url")
				.display-value= @google_adword.url
			%li.list-row
				.display-label= t("activerecord.attributes.google_adword.campaign_name")
				.display-value= @google_adword.campaign_name
			%li.list-row
				.display-label= t("activerecord.attributes.google_adword.description")
				.display-value= @google_adword.description
			%li.list-row
				.display-label= t("activerecord.attributes.google_adword.script")
				.display-value= @google_adword.script

			%li.list-row
				= link_to t('keppler.actions.back_history'), admin_google_adwords_path

:javascript
	$('.tooltipped').tooltip({delay: 1});

app/views/admin/google_adwords/_listing.html.haml
%tr{ id: "row-#{google_adword.id}" }
	- if can? :destroy_multiple, GoogleAdword
		%td.item-check{style:"width: 10%"}
			= link_to "", admin_google_adword_path(google_adword), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{google_adword.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{google_adword.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{google_adword.id}" }

		%td{style:"width: 30%"}
			= link_to "", admin_google_adword_path(google_adword, search: @query), remote: true, class: "show-row"
			%span
				= google_adword.url
		%td{style:"width: 30%"}
			= link_to "", admin_google_adword_path(google_adword, search: @query), remote: true, class: "show-row"
			%span
				= google_adword.campaign_name

	- if can? :clone, GoogleAdword
		%td{style:"width: 5%"}
			= link_to admin_google_adword_clone_path(google_adword), class: "btn-floating waves-effect btn-flat" do
				= material_icon.md_24.content_copy.css_class("md-dark")
	%td{style:"width: 5%"}
		= link_to admin_google_adword_path(google_adword), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/admin/google_adwords/edit.html.haml
= title(t('keppler.titles.edit', model: "Google adwords"))
= render 'form'

app/views/admin/google_adwords/index.html.haml
= title(t('keppler.titles.index', model: "Google adwords"))
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_admin_google_adword_path, class: "btn-add btn-floating btn-large waves-effect waves-light btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |google_adword|
				= render 'listing', google_adword: google_adword
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							= t('keppler.messages.not_found_records', model:  t("keppler.models.pluralize.google_adwords"))
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_admin_google_adword_path, class: "btn-add btn-index-add btn-floating btn-large waves-effect waves-light" do
		= material_icon.md_24.add.css_class("md-light")

app/views/admin/google_adwords/new.html.haml
= title(t('keppler.titles.new', model: "Google adwords"))
= render 'form'

app/views/admin/google_adwords/show.html.haml
= title(t('keppler.titles.show', model: "Google adwords"))
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, GoogleAdword
				= link_to admin_google_adword_path(@google_adword), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.delete"), method: :delete, data: { confirm: t("keppler.messages.data_confirm") } do
					= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, GoogleAdword
				= link_to edit_admin_google_adword_path(@google_adword), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" =>t("keppler.actions.edit") do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to admin_google_adwords_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.card
			.card-content
				%ul.list
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.id")
						.display-value.fs-body-1.tc-black-2= @google_adword.id.to_s.humanize
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.url")
						.display-value.fs-body-1.tc-black-2= @google_adword.url.to_s.humanize
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.campaign_name")
						.display-value.fs-body-1.tc-black-2= @google_adword.campaign_name.to_s.humanize
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.description")
						.display-value.fs-body-1.tc-black-2= @google_adword.description.to_s.humanize
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.script")
						.display-value.fs-body-1.tc-black-2= @google_adword.script.to_s.humanize

app/views/admin/google_adwords/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@google_adword.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");