config/routes.rb
Rails.application.routes.draw do
  root to: 'app/front#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  namespace :admin do
    root to: 'admin#root'

    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :meta_tags do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_adwords do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_analytics_tracks do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :settings, only: [] do
      collection do
        get '/:config', to: 'settings#edit', as: ''
        put '/:config', to: 'settings#update', as: 'update'
      end
    end
  end

  # Errors routes
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Dashboard route engine
  mount KepplerGaDashboard::Engine, at: 'admin/dashboard', as: 'dashboard'
end

app/models/google_analytics_track.rb
# GoogleAnayticsTrack Model
class GoogleAnalyticsTrack < ActiveRecord::Base
  include ActivityHistory

  def self.get_tracking_id(request)
    find_by_url(request.url)
  end

  def self.search_field
    :name_or_tracking_id_cont
  end
end

app/controllers/admin/google_analytics_tracks_controller.rb
module Admin
  # GoogleAnalyticsTracksController
  class GoogleAnalyticsTracksController < AdminController
    before_action :set_ga_track, only: [:show, :edit, :update, :destroy]
    before_action :show_history, only: [:index]

    # GET /google_analytics_tracks
    def index
      @q = GoogleAnalyticsTrack.ransack(params[:q])
      google_analytics_tracks = @q.result(distinct: true)
      @objects = google_analytics_tracks.page(@current_page)
      @total = google_analytics_tracks.size

      if !@objects.first_page? && @objects.size.zero?
        redirect_to(
          google_analytics_tracks_path(
            page: @current_page.to_i.pred,
            search: @query)
        )
      end
    end

    # GET /google_analytics_tracks/1
    def show
    end

    # GET /google_analytics_tracks/new
    def new
      @google_analytics_track = GoogleAnalyticsTrack.new
    end

    # GET /google_analytics_tracks/1/edit
    def edit
    end

    # POST /google_analytics_tracks
    def create
      @google_analytics_track =
        GoogleAnalyticsTrack.new(google_analytics_track_params)

      if @google_analytics_track.save
        redirect(@google_analytics_track, params)
      else
        render :new
      end
    end

    # PATCH/PUT /google_analytics_tracks/1
    def update
      if @google_analytics_track.update(google_analytics_track_params)
        redirect(@google_analytics_track, params)
      else
        render :edit
      end
    end

    # DELETE /google_analytics_tracks/1
    def destroy
      @google_analytics_track.destroy

      redirect_to(
        admin_google_analytics_tracks_path,
        notice: actions_messages(@google_analytics_track)
      )
    end

    def destroy_multiple
      GoogleAnalyticsTrack.destroy redefine_ids(params[:multiple_ids])

      redirect_to(
        admin_google_analytics_tracks_path(page: @current_page, search: @query),
        notice: actions_messages(GoogleAnalyticsTrack.new)
      )
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_ga_track
      @google_analytics_track = GoogleAnalyticsTrack.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def google_analytics_track_params
      params.require(:google_analytics_track).permit(:name, :tracking_id, :url)
    end

    def show_history
      get_history(GoogleAnalyticsTrack)
    end
  end
end

app/views/admin/google_analytics_tracks/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.insert_chart.css_class("md-light")
		= t("keppler.models.singularize.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list{style: "padding: 0px;"}
		.collection.with-header{style: "margin: 0px;"}
			.collection-header
				%h5.center-align
					= @activities.empty? ? t('keppler.messages.no_events') : t("keppler.titles.history")
			- @activities.each do |activity|
				- if activity.trackable_type.eql? "Session"
					= render partial: "public_activity/session/#{activity.key.split(".").second}", locals: { activity: activity, method: "name" }
				- else
					= render partial: "public_activity/layout/#{activity.key.split(".").second}", locals: { activity: activity, method: "name" }

app/views/admin/google_analytics_tracks/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to admin_google_analytics_tracks_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				.card-content
					= simple_form_for [:admin, @google_analytics_track] do |f|
						.row
							= f.input :name
							= f.input :tracking_id
							= f.input :url

							.form-actions.right
								= f.button :submit, t("keppler.actions.save"), name: "_save"
								= f.button :submit, t("keppler.actions.save_and_add_another"), name: "_add_other"

app/views/admin/google_analytics_tracks/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, GoogleAnalyticsTrack
			= link_to edit_admin_google_analytics_track_path(@google_analytics_track), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.edit") do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.insert_chart.css_class("md-light")
		= t("keppler.models.singularize.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.card-content
		%ul.list
			%li.list-row
				.display-label= t("activerecord.attributes.google_analytics_track.name")
				.display-value= @google_analytics_track.name
			%li.list-row
				.display-label= t("activerecord.attributes.google_analytics_track.tracking_id")
				.display-value= @google_analytics_track.tracking_id
			%li.list-row
				.display-label= t("activerecord.attributes.google_analytics_track.url")
				.display-value
					= link_to @google_analytics_track.url, @google_analytics_track.url, target: "_blank"

			%li.list-row
				= link_to t('keppler.actions.back_history'), admin_google_analytics_tracks_path

:javascript
	$('.tooltipped').tooltip({delay: 1});

app/views/admin/google_analytics_tracks/_listing.html.haml
%tr{ id: "row-#{google_analytics_track.id}" }
	- if can? :destroy_multiple, GoogleAnalyticsTrack
		%td.item-check{style:"width: 10%"}
			= link_to "", admin_google_analytics_track_path(google_analytics_track), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{google_analytics_track.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{google_analytics_track.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{google_analytics_track.id}" }

	%td{style:"width: 20%"}
		= link_to "", admin_google_analytics_track_path(google_analytics_track, search: @query), remote: true, class: "show-row"
		%span
			= google_analytics_track.name
	%td{style:"width: 20%"}
		= link_to "", admin_google_analytics_track_path(google_analytics_track, search: @query), remote: true, class: "show-row"
		%span
			= google_analytics_track.tracking_id
	%td{style:"width: 55%"}
		= link_to "", admin_google_analytics_track_path(google_analytics_track, search: @query), remote: true, class: "show-row"
		%span
			= google_analytics_track.url.truncate(100)

	%td{style:"width: 5%"}
		= link_to admin_google_analytics_track_path(google_analytics_track), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/admin/google_analytics_tracks/edit.html.haml
= title(t('keppler.titles.edit', model: "Google analytics tracks"))
= render 'form'

app/views/admin/google_analytics_tracks/index.html.haml
= title(t('keppler.titles.index', model: "Google analytics tracks"))
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_admin_google_analytics_track_path, class: "btn-add btn-floating btn-large waves-effect waves-light btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |google_analytics_track|
				= render 'listing', google_analytics_track: google_analytics_track
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							= t('keppler.messages.not_found_records', model:  t("keppler.models.pluralize.google_analytics_tracks"))
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_admin_google_analytics_track_path, class: "btn-add btn-index-add btn-floating btn-large waves-effect waves-light" do
		= material_icon.md_24.add.css_class("md-light")

app/views/admin/google_analytics_tracks/new.html.haml
= title(t('keppler.titles.new', model: "Google analytics tracks"))
= render 'form'

app/views/admin/google_analytics_tracks/show.html.haml
= title(t('keppler.titles.show', model: "Google analytics tracks"))
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, GoogleAnalyticsTrack
				= link_to admin_google_analytics_track_path(@google_analytics_track), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.delete"), method: :delete, data: { confirm: t("keppler.messages.data_confirm") } do
					= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, GoogleAnalyticsTrack
				= link_to edit_admin_google_analytics_track_path(@google_analytics_track), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" =>t("keppler.actions.edit") do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to admin_google_analytics_tracks_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.card
			.card-content
				%ul.list
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.id")
						.display-value.fs-body-1.tc-black-2= @google_analytics_track.id
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.name")
						.display-value.fs-body-1.tc-black-2= @google_analytics_track.name.humanize
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.tracking_id")
						.display-value.fs-body-1.tc-black-2= @google_analytics_track.tracking_id
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.url")
						.display-value.fs-body-1.tc-black-2
							= link_to @google_analytics_track.url, @google_analytics_track.url, target: "_blank"

app/views/admin/google_analytics_tracks/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@google_analytics_track.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");